-- Migration: Add AI-powered negotiations tables
-- Date: 2025-01-06

-- Drop existing tables if they exist (for clean migration)
DROP TABLE IF EXISTS negotiation_messages CASCADE;
DROP TABLE IF EXISTS negotiations CASCADE;

-- Create negotiations table
CREATE TABLE negotiations (
  id SERIAL PRIMARY KEY,
  uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
  project_id INTEGER NOT NULL REFERENCES projects(id),
  investor_id INTEGER NOT NULL REFERENCES users(id),
  owner_id INTEGER NOT NULL REFERENCES users(id),
  
  -- Negotiation details
  status VARCHAR(50) DEFAULT 'active' NOT NULL, -- active, completed, expired, cancelled
  started_at TIMESTAMP DEFAULT NOW(),
  expires_at TIMESTAMP,
  completed_at TIMESTAMP,
  
  -- Agreement
  agreement_reached BOOLEAN DEFAULT FALSE,
  suggested_terms JSONB, -- {investmentAmount, equity, expectedReturn, timeline}
  
  -- Metadata
  created_at TIMESTAMP DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Create negotiation_messages table
CREATE TABLE negotiation_messages (
  id SERIAL PRIMARY KEY,
  uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
  negotiation_id INTEGER NOT NULL REFERENCES negotiations(id) ON DELETE CASCADE,
  sender_id INTEGER NOT NULL REFERENCES users(id),
  
  -- Message content
  message TEXT NOT NULL,
  is_ai_generated BOOLEAN DEFAULT FALSE,
  
  -- Moderation
  flagged BOOLEAN DEFAULT FALSE, -- if contains contact info
  
  -- Metadata
  created_at TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Create indexes
CREATE INDEX negotiations_project_idx ON negotiations(project_id);
CREATE INDEX negotiations_investor_idx ON negotiations(investor_id);
CREATE INDEX negotiations_status_idx ON negotiations(status);
CREATE INDEX negotiation_messages_negotiation_idx ON negotiation_messages(negotiation_id);
CREATE INDEX negotiation_messages_sender_idx ON negotiation_messages(sender_id);

-- Add comments
COMMENT ON TABLE negotiations IS 'AI-powered negotiation sessions between investors and project owners';
COMMENT ON TABLE negotiation_messages IS 'Messages exchanged during AI-powered negotiations';
COMMENT ON COLUMN negotiation_messages.is_ai_generated IS 'True if message was generated by AI agent';
COMMENT ON COLUMN negotiation_messages.flagged IS 'True if message contains contact information or violates rules';
