// نظام Sandbox المتكامل - بيانات وهمية شاملة لجميع أجزاء التطبيق

// ============ المستخدمون ============
export const sandboxUsers = [
  {
    id: '1',
    name: 'أحمد محمد السعيد',
    email: 'ahmed.saeed@example.com',
    username: 'ahmed_saeed',
    phone: '+966501234567',
    role: 'admin',
    status: 'active',
    level: 10,
    points: 15000,
    verified: true,
    walletBalance: '250000',
    totalProjects: 8,
    totalInvestments: 25,
    totalEarnings: '500000',
    joinedAt: '2024-01-01T10:00:00Z',
    lastActive: '2025-10-18T14:00:00Z',
  },
  {
    id: '2',
    name: 'فاطمة عبدالله النور',
    email: 'fatima.noor@example.com',
    username: 'fatima_noor',
    phone: '+966502345678',
    role: 'investor',
    status: 'active',
    level: 9,
    points: 12000,
    verified: true,
    walletBalance: '180000',
    totalProjects: 2,
    totalInvestments: 35,
    totalEarnings: '420000',
    joinedAt: '2024-01-15T10:00:00Z',
    lastActive: '2025-10-18T13:30:00Z',
  },
  {
    id: '3',
    name: 'خالد عمر الشمري',
    email: 'khaled.shamri@example.com',
    username: 'khaled_omar',
    phone: '+966503456789',
    role: 'marketer',
    status: 'active',
    level: 8,
    points: 9500,
    verified: true,
    walletBalance: '95000',
    totalProjects: 0,
    totalInvestments: 18,
    totalEarnings: '145000',
    joinedAt: '2024-02-01T10:00:00Z',
    lastActive: '2025-10-18T12:00:00Z',
  },
  {
    id: '4',
    name: 'سارة حسن القحطاني',
    email: 'sarah.qahtani@example.com',
    username: 'sarah_hassan',
    phone: '+966504567890',
    role: 'user',
    status: 'active',
    level: 7,
    points: 7200,
    verified: true,
    walletBalance: '65000',
    totalProjects: 5,
    totalInvestments: 12,
    totalEarnings: '98000',
    joinedAt: '2024-02-15T10:00:00Z',
    lastActive: '2025-10-18T11:00:00Z',
  },
  {
    id: '5',
    name: 'محمد علي الدوسري',
    email: 'mohammed.dosari@example.com',
    username: 'mohammed_ali',
    phone: '+966505678901',
    role: 'investor',
    status: 'active',
    level: 9,
    points: 11000,
    verified: true,
    walletBalance: '150000',
    totalProjects: 3,
    totalInvestments: 28,
    totalEarnings: '320000',
    joinedAt: '2024-03-01T10:00:00Z',
    lastActive: '2025-10-18T10:30:00Z',
  },
  {
    id: '6',
    name: 'نورة سعد العتيبي',
    email: 'noura.otaibi@example.com',
    username: 'noura_saad',
    phone: '+966506789012',
    role: 'user',
    status: 'active',
    level: 6,
    points: 5800,
    verified: true,
    walletBalance: '45000',
    totalProjects: 4,
    totalInvestments: 8,
    totalEarnings: '62000',
    joinedAt: '2024-03-15T10:00:00Z',
    lastActive: '2025-10-18T09:00:00Z',
  },
  {
    id: '7',
    name: 'عبدالله يوسف المطيري',
    email: 'abdullah.mutairi@example.com',
    username: 'abdullah_youssef',
    phone: '+966507890123',
    role: 'user',
    status: 'active',
    level: 5,
    points: 4200,
    verified: true,
    walletBalance: '32000',
    totalProjects: 3,
    totalInvestments: 6,
    totalEarnings: '48000',
    joinedAt: '2024-04-01T10:00:00Z',
    lastActive: '2025-10-17T18:00:00Z',
  },
  {
    id: '8',
    name: 'مريم أحمد الحربي',
    email: 'maryam.harbi@example.com',
    username: 'maryam_ahmed',
    phone: '+966508901234',
    role: 'marketer',
    status: 'active',
    level: 7,
    points: 6800,
    verified: true,
    walletBalance: '58000',
    totalProjects: 1,
    totalInvestments: 15,
    totalEarnings: '85000',
    joinedAt: '2024-04-15T10:00:00Z',
    lastActive: '2025-10-17T16:00:00Z',
  },
];

// ============ المشاريع ============
export const sandboxProjects = [
  {
    id: '1',
    title: 'منصة التعليم الإلكتروني المتقدمة',
    description: 'منصة تعليمية شاملة تستخدم الذكاء الاصطناعي لتخصيص تجربة التعلم لكل طالب',
    category: 'تقنية',
    targetAmount: '500000',
    currentAmount: '425000',
    progress: 85,
    backers: 145,
    daysLeft: 12,
    status: 'active',
    featured: true,
    trending: true,
    creatorId: '1',
    creatorName: 'أحمد محمد السعيد',
    creatorAvatar: 'A',
    image: '/images/projects/education-platform.jpg',
    tags: ['تعليم', 'ذكاء اصطناعي', 'تقنية'],
    createdAt: '2025-09-01T10:00:00Z',
    updatedAt: '2025-10-18T10:00:00Z',
  },
  {
    id: '2',
    title: 'تطبيق التوصيل الصحي',
    description: 'تطبيق لتوصيل الأدوية والمستلزمات الطبية خلال ساعة واحدة',
    category: 'صحة',
    targetAmount: '300000',
    currentAmount: '280000',
    progress: 93,
    backers: 98,
    daysLeft: 5,
    status: 'active',
    featured: true,
    trending: false,
    creatorId: '2',
    creatorName: 'فاطمة عبدالله النور',
    creatorAvatar: 'ف',
    image: '/images/projects/health-delivery.jpg',
    tags: ['صحة', 'توصيل', 'تطبيق'],
    createdAt: '2025-09-10T10:00:00Z',
    updatedAt: '2025-10-18T09:00:00Z',
  },
  {
    id: '3',
    title: 'مشروع الزراعة الذكية',
    description: 'نظام زراعي متطور يستخدم IoT لمراقبة وإدارة المزارع تلقائياً',
    category: 'زراعة',
    targetAmount: '400000',
    currentAmount: '320000',
    progress: 80,
    backers: 76,
    daysLeft: 18,
    status: 'active',
    featured: false,
    trending: true,
    creatorId: '4',
    creatorName: 'سارة حسن القحطاني',
    creatorAvatar: 'س',
    image: '/images/projects/smart-farming.jpg',
    tags: ['زراعة', 'IoT', 'تقنية'],
    createdAt: '2025-09-15T10:00:00Z',
    updatedAt: '2025-10-18T08:00:00Z',
  },
  {
    id: '4',
    title: 'منصة التجارة الإلكترونية المحلية',
    description: 'منصة تربط المنتجين المحليين بالمستهلكين مباشرة',
    category: 'تجارة',
    targetAmount: '250000',
    currentAmount: '180000',
    progress: 72,
    backers: 62,
    daysLeft: 25,
    status: 'active',
    featured: false,
    trending: false,
    creatorId: '5',
    creatorName: 'محمد علي الدوسري',
    creatorAvatar: 'م',
    image: '/images/projects/local-ecommerce.jpg',
    tags: ['تجارة', 'محلي', 'منصة'],
    createdAt: '2025-09-20T10:00:00Z',
    updatedAt: '2025-10-17T18:00:00Z',
  },
  {
    id: '5',
    title: 'تطبيق إدارة المهام الذكي',
    description: 'تطبيق يساعد الأفراد والفرق على تنظيم مهامهم بكفاءة عالية',
    category: 'إنتاجية',
    targetAmount: '150000',
    currentAmount: '95000',
    progress: 63,
    backers: 48,
    daysLeft: 30,
    status: 'active',
    featured: false,
    trending: true,
    creatorId: '6',
    creatorName: 'نورة سعد العتيبي',
    creatorAvatar: 'ن',
    image: '/images/projects/task-manager.jpg',
    tags: ['إنتاجية', 'تطبيق', 'إدارة'],
    createdAt: '2025-10-01T10:00:00Z',
    updatedAt: '2025-10-17T16:00:00Z',
  },
  {
    id: '6',
    title: 'مشروع الطاقة الشمسية المنزلية',
    description: 'حلول طاقة شمسية مبتكرة للمنازل بأسعار معقولة',
    category: 'طاقة',
    targetAmount: '600000',
    currentAmount: '450000',
    progress: 75,
    backers: 112,
    daysLeft: 20,
    status: 'active',
    featured: true,
    trending: false,
    creatorId: '1',
    creatorName: 'أحمد محمد السعيد',
    creatorAvatar: 'A',
    image: '/images/projects/solar-energy.jpg',
    tags: ['طاقة', 'شمسية', 'بيئة'],
    createdAt: '2025-08-15T10:00:00Z',
    updatedAt: '2025-10-17T14:00:00Z',
  },
  {
    id: '7',
    title: 'منصة الاستشارات القانونية',
    description: 'منصة تربط المحامين بالعملاء لتقديم استشارات قانونية فورية',
    category: 'خدمات',
    targetAmount: '200000',
    currentAmount: '140000',
    progress: 70,
    backers: 54,
    daysLeft: 15,
    status: 'active',
    featured: false,
    trending: false,
    creatorId: '7',
    creatorName: 'عبدالله يوسف المطيري',
    creatorAvatar: 'ع',
    image: '/images/projects/legal-platform.jpg',
    tags: ['قانون', 'استشارات', 'خدمات'],
    createdAt: '2025-09-25T10:00:00Z',
    updatedAt: '2025-10-17T12:00:00Z',
  },
  {
    id: '8',
    title: 'تطبيق اللياقة البدنية الشخصي',
    description: 'تطبيق يوفر برامج تدريب مخصصة ومتابعة صحية شاملة',
    category: 'صحة',
    targetAmount: '180000',
    currentAmount: '125000',
    progress: 69,
    backers: 67,
    daysLeft: 22,
    status: 'active',
    featured: false,
    trending: true,
    creatorId: '8',
    creatorName: 'مريم أحمد الحربي',
    creatorAvatar: 'م',
    image: '/images/projects/fitness-app.jpg',
    tags: ['صحة', 'لياقة', 'تطبيق'],
    createdAt: '2025-09-30T10:00:00Z',
    updatedAt: '2025-10-17T10:00:00Z',
  },
];

// ============ المجتمعات ============
export const sandboxCommunities = [
  {
    id: '1',
    name: 'مجتمع رواد الأعمال التقنيين',
    description: 'مجتمع لرواد الأعمال المهتمين بالتقنية والابتكار',
    category: 'تقنية',
    memberCount: 1250,
    postsCount: 485,
    status: 'active',
    isPrivate: false,
    creatorId: '1',
    creatorName: 'أحمد محمد السعيد',
    image: '/images/communities/tech-entrepreneurs.jpg',
    tags: ['تقنية', 'ريادة أعمال', 'ابتكار'],
    createdAt: '2024-06-01T10:00:00Z',
    updatedAt: '2025-10-18T10:00:00Z',
  },
  {
    id: '2',
    name: 'مجتمع المستثمرين الملائكة',
    description: 'مجتمع للمستثمرين الراغبين في دعم المشاريع الناشئة',
    category: 'استثمار',
    memberCount: 850,
    postsCount: 320,
    status: 'active',
    isPrivate: true,
    creatorId: '2',
    creatorName: 'فاطمة عبدالله النور',
    image: '/images/communities/angel-investors.jpg',
    tags: ['استثمار', 'تمويل', 'مشاريع ناشئة'],
    createdAt: '2024-07-01T10:00:00Z',
    updatedAt: '2025-10-18T09:00:00Z',
  },
  {
    id: '3',
    name: 'مجتمع المسوقين الرقميين',
    description: 'مجتمع لمحترفي التسويق الرقمي ووسائل التواصل الاجتماعي',
    category: 'تسويق',
    memberCount: 2100,
    postsCount: 890,
    status: 'active',
    isPrivate: false,
    creatorId: '3',
    creatorName: 'خالد عمر الشمري',
    image: '/images/communities/digital-marketers.jpg',
    tags: ['تسويق', 'رقمي', 'سوشيال ميديا'],
    createdAt: '2024-05-15T10:00:00Z',
    updatedAt: '2025-10-18T08:00:00Z',
  },
  {
    id: '4',
    name: 'مجتمع المطورين السعوديين',
    description: 'مجتمع للمطورين والمبرمجين في المملكة',
    category: 'برمجة',
    memberCount: 3200,
    postsCount: 1520,
    status: 'active',
    isPrivate: false,
    creatorId: '5',
    creatorName: 'محمد علي الدوسري',
    image: '/images/communities/saudi-developers.jpg',
    tags: ['برمجة', 'تطوير', 'تقنية'],
    createdAt: '2024-04-01T10:00:00Z',
    updatedAt: '2025-10-17T18:00:00Z',
  },
  {
    id: '5',
    name: 'مجتمع الاقتصاد الأخضر',
    description: 'مجتمع للمهتمين بالمشاريع البيئية والطاقة المتجددة',
    category: 'بيئة',
    memberCount: 950,
    postsCount: 380,
    status: 'active',
    isPrivate: false,
    creatorId: '4',
    creatorName: 'سارة حسن القحطاني',
    image: '/images/communities/green-economy.jpg',
    tags: ['بيئة', 'طاقة متجددة', 'استدامة'],
    createdAt: '2024-08-01T10:00:00Z',
    updatedAt: '2025-10-17T16:00:00Z',
  },
];

// ============ الفعاليات ============
export const sandboxEvents = [
  {
    id: '1',
    title: 'ملتقى رواد الأعمال 2025',
    description: 'ملتقى سنوي يجمع رواد الأعمال والمستثمرين',
    date: '2025-11-15T09:00:00Z',
    location: 'الرياض - مركز الملك عبدالله المالي',
    attendees: 450,
    maxAttendees: 500,
    status: 'upcoming',
    category: 'ملتقى',
    organizerId: '1',
    organizerName: 'أحمد محمد السعيد',
    image: '/images/events/entrepreneurs-summit.jpg',
    tags: ['ريادة أعمال', 'استثمار', 'شبكات'],
    createdAt: '2025-09-01T10:00:00Z',
  },
  {
    id: '2',
    title: 'ورشة عمل: التسويق الرقمي الفعال',
    description: 'ورشة عمل عملية لتعلم استراتيجيات التسويق الرقمي',
    date: '2025-10-25T14:00:00Z',
    location: 'جدة - مركز الأعمال',
    attendees: 85,
    maxAttendees: 100,
    status: 'upcoming',
    category: 'ورشة عمل',
    organizerId: '3',
    organizerName: 'خالد عمر الشمري',
    image: '/images/events/digital-marketing-workshop.jpg',
    tags: ['تسويق', 'ورشة عمل', 'تدريب'],
    createdAt: '2025-09-20T10:00:00Z',
  },
  {
    id: '3',
    title: 'هاكاثون الابتكار التقني',
    description: 'مسابقة برمجية لمدة 48 ساعة لحل تحديات تقنية',
    date: '2025-11-01T09:00:00Z',
    location: 'الدمام - جامعة الملك فهد',
    attendees: 180,
    maxAttendees: 200,
    status: 'upcoming',
    category: 'هاكاثون',
    organizerId: '5',
    organizerName: 'محمد علي الدوسري',
    image: '/images/events/tech-hackathon.jpg',
    tags: ['برمجة', 'هاكاثون', 'ابتكار'],
    createdAt: '2025-09-15T10:00:00Z',
  },
  {
    id: '4',
    title: 'لقاء المستثمرين الشهري',
    description: 'لقاء شهري لعرض المشاريع الناشئة على المستثمرين',
    date: '2025-10-28T18:00:00Z',
    location: 'الرياض - فندق الفيصلية',
    attendees: 65,
    maxAttendees: 80,
    status: 'upcoming',
    category: 'لقاء',
    organizerId: '2',
    organizerName: 'فاطمة عبدالله النور',
    image: '/images/events/investors-meetup.jpg',
    tags: ['استثمار', 'شبكات', 'مشاريع ناشئة'],
    createdAt: '2025-10-01T10:00:00Z',
  },
];

// ============ لوحة الصدارة ============
export const sandboxLeaderboard = [
  {
    rank: 1,
    userId: '1',
    name: 'أحمد محمد السعيد',
    avatar: 'A',
    points: 15000,
    level: 10,
    badge: 'ذهبي',
    achievements: 45,
    projectsCreated: 8,
    investmentsMade: 25,
  },
  {
    rank: 2,
    userId: '2',
    name: 'فاطمة عبدالله النور',
    avatar: 'ف',
    points: 12000,
    level: 9,
    badge: 'فضي',
    achievements: 38,
    projectsCreated: 2,
    investmentsMade: 35,
  },
  {
    rank: 3,
    userId: '5',
    name: 'محمد علي الدوسري',
    avatar: 'م',
    points: 11000,
    level: 9,
    badge: 'فضي',
    achievements: 36,
    projectsCreated: 3,
    investmentsMade: 28,
  },
  {
    rank: 4,
    userId: '3',
    name: 'خالد عمر الشمري',
    avatar: 'خ',
    points: 9500,
    level: 8,
    badge: 'برونزي',
    achievements: 32,
    projectsCreated: 0,
    investmentsMade: 18,
  },
  {
    rank: 5,
    userId: '4',
    name: 'سارة حسن القحطاني',
    avatar: 'س',
    points: 7200,
    level: 7,
    badge: 'برونزي',
    achievements: 28,
    projectsCreated: 5,
    investmentsMade: 12,
  },
];

// ============ التفاوضات ============
export const sandboxNegotiations = [
  {
    id: '1',
    projectId: '1',
    projectTitle: 'منصة التعليم الإلكتروني المتقدمة',
    investorId: '2',
    investorName: 'فاطمة عبدالله النور',
    creatorId: '1',
    creatorName: 'أحمد محمد السعيد',
    amount: '100000',
    equity: 15,
    status: 'pending',
    messages: 8,
    lastMessage: 'أنا مهتمة بالاستثمار، لكن أود مناقشة نسبة الأسهم',
    createdAt: '2025-10-15T10:00:00Z',
    updatedAt: '2025-10-18T09:00:00Z',
  },
  {
    id: '2',
    projectId: '3',
    projectTitle: 'مشروع الزراعة الذكية',
    investorId: '5',
    investorName: 'محمد علي الدوسري',
    creatorId: '4',
    creatorName: 'سارة حسن القحطاني',
    amount: '80000',
    equity: 12,
    status: 'accepted',
    messages: 15,
    lastMessage: 'تم الاتفاق على الشروط، سنبدأ بإجراءات التعاقد',
    createdAt: '2025-10-10T10:00:00Z',
    updatedAt: '2025-10-17T16:00:00Z',
  },
  {
    id: '3',
    projectId: '2',
    projectTitle: 'تطبيق التوصيل الصحي',
    investorId: '3',
    investorName: 'خالد عمر الشمري',
    creatorId: '2',
    creatorName: 'فاطمة عبدالله النور',
    amount: '50000',
    equity: 8,
    status: 'rejected',
    messages: 5,
    lastMessage: 'شكراً على الاهتمام، لكن العرض لا يتناسب مع توقعاتنا',
    createdAt: '2025-10-12T10:00:00Z',
    updatedAt: '2025-10-16T14:00:00Z',
  },
];

// ============ الإحصائيات ============
export const sandboxStats = {
  users: {
    total: 8,
    active: 8,
    inactive: 0,
    suspended: 0,
    newThisMonth: 2,
    verified: 7,
  },
  projects: {
    total: 8,
    active: 8,
    funded: 2,
    pending: 0,
    featured: 3,
    trending: 4,
    totalFunding: '2015000',
    totalBackers: 662,
  },
  communities: {
    total: 5,
    active: 5,
    totalMembers: 8350,
    totalPosts: 3595,
  },
  events: {
    total: 4,
    upcoming: 4,
    past: 0,
    totalAttendees: 780,
  },
  negotiations: {
    total: 3,
    pending: 1,
    accepted: 1,
    rejected: 1,
  },
  platform: {
    totalRevenue: '2500000',
    totalTransactions: 856,
    averageProjectFunding: '251875',
    successRate: 75,
  },
};

