// Sandbox dummy data for testing purposes

export const sandboxUsers = [
  {
    id: '1',
    name: 'أحمد محمد السعيد',
    email: 'ahmed@example.com',
    phone: '+966501234567',
    role: 'user',
    status: 'active',
    level: 5,
    points: 2500,
    verified: true,
    walletBalance: '15000',
    totalProjects: 3,
    totalInvestments: 8,
    totalEarnings: '25000',
    joinedAt: '2024-01-15T10:00:00Z',
    lastActive: '2025-10-18T12:00:00Z',
  },
  {
    id: '2',
    name: 'فاطمة عبدالله النور',
    email: 'fatima@example.com',
    phone: '+966502345678',
    role: 'investor',
    status: 'active',
    level: 8,
    points: 5000,
    verified: true,
    walletBalance: '50000',
    totalProjects: 1,
    totalInvestments: 15,
    totalEarnings: '75000',
    joinedAt: '2024-02-20T10:00:00Z',
    lastActive: '2025-10-18T11:30:00Z',
  },
  {
    id: '3',
    name: 'خالد عمر الشمري',
    email: 'khaled@example.com',
    phone: '+966503456789',
    role: 'marketer',
    status: 'active',
    level: 6,
    points: 3200,
    verified: true,
    walletBalance: '8500',
    totalProjects: 0,
    totalInvestments: 5,
    totalEarnings: '12000',
    joinedAt: '2024-03-10T10:00:00Z',
    lastActive: '2025-10-18T10:00:00Z',
  },
  {
    id: '4',
    name: 'سارة حسن القحطاني',
    email: 'sarah@example.com',
    phone: '+966504567890',
    role: 'user',
    status: 'active',
    level: 4,
    points: 1800,
    verified: false,
    walletBalance: '3200',
    totalProjects: 2,
    totalInvestments: 3,
    totalEarnings: '5000',
    joinedAt: '2024-04-05T10:00:00Z',
    lastActive: '2025-10-17T15:00:00Z',
  },
  {
    id: '5',
    name: 'محمد علي الدوسري',
    email: 'mohammed@example.com',
    phone: '+966505678901',
    role: 'admin',
    status: 'active',
    level: 10,
    points: 10000,
    verified: true,
    walletBalance: '100000',
    totalProjects: 5,
    totalInvestments: 20,
    totalEarnings: '150000',
    joinedAt: '2024-01-01T10:00:00Z',
    lastActive: '2025-10-18T13:00:00Z',
  },
  {
    id: '6',
    name: 'نورة سعد العتيبي',
    email: 'noura@example.com',
    phone: '+966506789012',
    role: 'user',
    status: 'inactive',
    level: 2,
    points: 500,
    verified: false,
    walletBalance: '0',
    totalProjects: 0,
    totalInvestments: 1,
    totalEarnings: '0',
    joinedAt: '2024-08-15T10:00:00Z',
    lastActive: '2024-09-01T10:00:00Z',
  },
];

export const sandboxProjects = [
  {
    id: '1',
    title: 'منصة تعليمية تفاعلية للأطفال',
    description: 'منصة تعليمية مبتكرة تستخدم الذكاء الاصطناعي لتقديم تجربة تعليمية مخصصة لكل طفل',
    category: 'تقنية',
    status: 'active',
    fundingGoal: '100000',
    currentFunding: '75000',
    backersCount: 45,
    creatorName: 'أحمد محمد السعيد',
    createdAt: '2024-09-01T10:00:00Z',
    deadline: '2025-12-31T23:59:59Z',
  },
  {
    id: '2',
    title: 'تطبيق توصيل صحي للوجبات',
    description: 'تطبيق يربط بين الطهاة المحترفين والعملاء الباحثين عن وجبات صحية ومغذية',
    category: 'أعمال',
    status: 'active',
    fundingGoal: '150000',
    currentFunding: '120000',
    backersCount: 68,
    creatorName: 'فاطمة عبدالله النور',
    createdAt: '2024-08-15T10:00:00Z',
    deadline: '2025-11-30T23:59:59Z',
  },
  {
    id: '3',
    title: 'مشروع زراعة عضوية مستدامة',
    description: 'مزرعة عضوية تستخدم تقنيات الزراعة المستدامة لإنتاج خضروات وفواكه صحية',
    category: 'اجتماعية',
    status: 'pending',
    fundingGoal: '80000',
    currentFunding: '15000',
    backersCount: 12,
    creatorName: 'سارة حسن القحطاني',
    createdAt: '2025-10-10T10:00:00Z',
    deadline: '2026-03-31T23:59:59Z',
  },
  {
    id: '4',
    title: 'استوديو تصميم جرافيكي متخصص',
    description: 'استوديو إبداعي يقدم خدمات تصميم الهوية البصرية والإعلانات للشركات الناشئة',
    category: 'إبداعية',
    status: 'funded',
    fundingGoal: '50000',
    currentFunding: '55000',
    backersCount: 32,
    creatorName: 'خالد عمر الشمري',
    createdAt: '2024-07-01T10:00:00Z',
    deadline: '2025-01-31T23:59:59Z',
  },
  {
    id: '5',
    title: 'منصة تواصل للمستقلين العرب',
    description: 'شبكة اجتماعية مهنية تربط المستقلين بالعملاء وتوفر أدوات لإدارة المشاريع',
    category: 'تقنية',
    status: 'active',
    fundingGoal: '200000',
    currentFunding: '95000',
    backersCount: 78,
    creatorName: 'محمد علي الدوسري',
    createdAt: '2024-06-01T10:00:00Z',
    deadline: '2025-12-31T23:59:59Z',
  },
  {
    id: '6',
    title: 'مشروع إعادة تدوير البلاستيك',
    description: 'مبادرة بيئية لجمع وإعادة تدوير البلاستيك وتحويله إلى منتجات مفيدة',
    category: 'اجتماعية',
    status: 'rejected',
    fundingGoal: '120000',
    currentFunding: '5000',
    backersCount: 3,
    creatorName: 'نورة سعد العتيبي',
    createdAt: '2024-09-20T10:00:00Z',
    deadline: '2025-06-30T23:59:59Z',
  },
];

export const sandboxWallets = [
  {
    id: '1',
    userName: 'أحمد محمد السعيد',
    userEmail: 'ahmed@example.com',
    balance: '15000',
    totalDeposits: '40000',
    totalWithdrawals: '25000',
    status: 'active',
  },
  {
    id: '2',
    userName: 'فاطمة عبدالله النور',
    userEmail: 'fatima@example.com',
    balance: '50000',
    totalDeposits: '125000',
    totalWithdrawals: '75000',
    status: 'active',
  },
  {
    id: '3',
    userName: 'خالد عمر الشمري',
    userEmail: 'khaled@example.com',
    balance: '8500',
    totalDeposits: '20000',
    totalWithdrawals: '11500',
    status: 'active',
  },
  {
    id: '4',
    userName: 'سارة حسن القحطاني',
    userEmail: 'sarah@example.com',
    balance: '3200',
    totalDeposits: '8000',
    totalWithdrawals: '4800',
    status: 'active',
  },
  {
    id: '5',
    userName: 'محمد علي الدوسري',
    userEmail: 'mohammed@example.com',
    balance: '100000',
    totalDeposits: '250000',
    totalWithdrawals: '150000',
    status: 'active',
  },
  {
    id: '6',
    userName: 'نورة سعد العتيبي',
    userEmail: 'noura@example.com',
    balance: '0',
    totalDeposits: '1000',
    totalWithdrawals: '1000',
    status: 'frozen',
  },
];

export const sandboxCommunities = [
  {
    id: '1',
    name: 'مجتمع رواد الأعمال السعوديين',
    description: 'مجتمع يجمع رواد الأعمال لتبادل الخبرات والفرص',
    category: 'أعمال',
    memberCount: 1250,
    postsCount: 3420,
    status: 'active',
    creatorName: 'محمد علي الدوسري',
  },
  {
    id: '2',
    name: 'مطورو التطبيقات العرب',
    description: 'مجتمع للمطورين لمشاركة الكود والمشاريع',
    category: 'تقنية',
    memberCount: 2100,
    postsCount: 5680,
    status: 'active',
    creatorName: 'أحمد محمد السعيد',
  },
  {
    id: '3',
    name: 'المستثمرون الملائكة',
    description: 'شبكة للمستثمرين الباحثين عن فرص استثمارية',
    category: 'استثمار',
    memberCount: 450,
    postsCount: 890,
    status: 'active',
    creatorName: 'فاطمة عبدالله النور',
  },
  {
    id: '4',
    name: 'المبدعون والفنانون',
    description: 'مجتمع للفنانين والمصممين لعرض أعمالهم',
    category: 'إبداعية',
    memberCount: 780,
    postsCount: 2340,
    status: 'active',
    creatorName: 'خالد عمر الشمري',
  },
  {
    id: '5',
    name: 'مجتمع الزراعة المستدامة',
    description: 'مجتمع يهتم بالزراعة العضوية والمستدامة',
    category: 'اجتماعية',
    memberCount: 320,
    postsCount: 650,
    status: 'inactive',
    creatorName: 'سارة حسن القحطاني',
  },
];

export const sandboxStats = {
  users: {
    total: 6,
    active: 5,
    inactive: 1,
    suspended: 0,
    newThisMonth: 0,
    verified: 4,
  },
  projects: {
    total: 6,
    pending: 1,
    active: 3,
    funded: 1,
    rejected: 1,
    totalFunding: '365000',
  },
  wallets: {
    total: 6,
    totalBalance: '176700',
    totalDeposits: '444000',
    totalWithdrawals: '267300',
  },
  communities: {
    total: 5,
    active: 4,
    totalMembers: 4900,
    totalPosts: 13980,
  },
};

